/*----- PROTECTED REGION ID(MoenchControl.cpp) ENABLED START -----*/
/* clang-format on */
//=============================================================================
//
// file :        MoenchControl.cpp
//
// description : C++ source for the MoenchControl class and its commands.
//               The class is derived from Device. It represents the
//               CORBA servant object which will be accessed from the
//               network. All commands which can be executed on the
//               MoenchControl are implemented in this file.
//
// project :     Tango device for control of MOENCH detector
//
// This file is part of Tango device class.
//
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
//
//
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================


#include "MoenchControl.h"
#include "MoenchControlClass.h"
/* clang-format off */
/*----- PROTECTED REGION END -----*/	//	MoenchControl.cpp

/**
 *  MoenchControl class description:
 *    
 */

//================================================================
//  The following table gives the correspondence
//  between command and method names.
//
//  Command name  |  Method name
//================================================================
//  State         |  Inherited (no method)
//  Status        |  Inherited (no method)
//================================================================

//================================================================
//  Attributes managed are:
//================================================================
//  exposure            |  Tango::DevFloat	Scalar
//  delay               |  Tango::DevFloat	Scalar
//  timing_mode         |  Tango::DevEnum	Scalar
//  triggers            |  Tango::DevLong64	Scalar
//  frames              |  Tango::DevLong64	Scalar
//  high_voltage        |  Tango::DevLong64	Scalar
//  gain_mode           |  Tango::DevEnum	Scalar
//  period              |  Tango::DevFloat	Scalar
//  zmq_rx_ip           |  Tango::DevString	Scalar
//  zmq_rx_port         |  Tango::DevLong64	Scalar
//  rx_discard_policy   |  Tango::DevEnum	Scalar
//  rx_hostname         |  Tango::DevString	Scalar
//  rx_tcp_port         |  Tango::DevLong64	Scalar
//  detector_status     |  Tango::DevEnum	Scalar
//  rx_zmq_data_stream  |  Tango::DevBoolean	Scalar
//================================================================

namespace MoenchControl_ns
{
/*----- PROTECTED REGION ID(MoenchControl::namespace_starting) ENABLED START -----*/
/* clang-format on */
//	static initializations
/* clang-format off */
/*----- PROTECTED REGION END -----*/	//	MoenchControl::namespace_starting

//--------------------------------------------------------
/**
 *	Method      : MoenchControl::MoenchControl()
 * Description:  Constructors for a Tango device
 *                implementing the classMoenchControl
 */
//--------------------------------------------------------
MoenchControl::MoenchControl(Tango::DeviceClass *cl, std::string &s)
 : TANGO_BASE_CLASS(cl, s.c_str())
{
	/*----- PROTECTED REGION ID(MoenchControl::constructor_1) ENABLED START -----*/
	/* clang-format on */
	init_device();
	/* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	MoenchControl::constructor_1
}
//--------------------------------------------------------
MoenchControl::MoenchControl(Tango::DeviceClass *cl, const char *s)
 : TANGO_BASE_CLASS(cl, s)
{
	/*----- PROTECTED REGION ID(MoenchControl::constructor_2) ENABLED START -----*/
	/* clang-format on */
	init_device();
	/* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	MoenchControl::constructor_2
}
//--------------------------------------------------------
MoenchControl::MoenchControl(Tango::DeviceClass *cl, const char *s, const char *d)
 : TANGO_BASE_CLASS(cl, s, d)
{
	/*----- PROTECTED REGION ID(MoenchControl::constructor_3) ENABLED START -----*/
	/* clang-format on */
	init_device();
	/* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	MoenchControl::constructor_3
}
//--------------------------------------------------------
MoenchControl::~MoenchControl()
{
	delete_device();
}

//--------------------------------------------------------
/**
 *	Method      : MoenchControl::delete_device()
 * Description:  will be called at device destruction or at init command
 */
//--------------------------------------------------------
void MoenchControl::delete_device()
{
	DEBUG_STREAM << "MoenchControl::delete_device() " << device_name << std::endl;
	/*----- PROTECTED REGION ID(MoenchControl::delete_device) ENABLED START -----*/
	/* clang-format on */
	//	Delete device allocated objects
	/* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	MoenchControl::delete_device
	delete[] attr_exposure_read;
	delete[] attr_delay_read;
	delete[] attr_timing_mode_read;
	delete[] attr_triggers_read;
	delete[] attr_frames_read;
	delete[] attr_high_voltage_read;
	delete[] attr_gain_mode_read;
	delete[] attr_period_read;
	delete[] attr_zmq_rx_ip_read;
	delete[] attr_zmq_rx_port_read;
	delete[] attr_rx_discard_policy_read;
	delete[] attr_rx_hostname_read;
	delete[] attr_rx_tcp_port_read;
	delete[] attr_detector_status_read;
	delete[] attr_rx_zmq_data_stream_read;
}

//--------------------------------------------------------
/**
 *	Method      : MoenchControl::init_device()
 * Description:  will be called at device initialization.
 */
//--------------------------------------------------------
void MoenchControl::init_device()
{
	DEBUG_STREAM << "MoenchControl::init_device() create device " << device_name << std::endl;
	/*----- PROTECTED REGION ID(MoenchControl::init_device_before) ENABLED START -----*/
	/* clang-format on */
	//	Initialization before get_device_property() call
	/* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	MoenchControl::init_device_before


	//	Get the device properties from database
	get_device_property();

	attr_exposure_read = new Tango::DevFloat[1];
	attr_delay_read = new Tango::DevFloat[1];
	attr_timing_mode_read = new timing_modeEnum[1];
	attr_triggers_read = new Tango::DevLong64[1];
	attr_frames_read = new Tango::DevLong64[1];
	attr_high_voltage_read = new Tango::DevLong64[1];
	attr_gain_mode_read = new gain_modeEnum[1];
	attr_period_read = new Tango::DevFloat[1];
	attr_zmq_rx_ip_read = new Tango::DevString[1];
	attr_zmq_rx_port_read = new Tango::DevLong64[1];
	attr_rx_discard_policy_read = new rx_discard_policyEnum[1];
	attr_rx_hostname_read = new Tango::DevString[1];
	attr_rx_tcp_port_read = new Tango::DevLong64[1];
	attr_detector_status_read = new detector_statusEnum[1];
	attr_rx_zmq_data_stream_read = new Tango::DevBoolean[1];
	//	No longer if mandatory property not set.
	if (mandatoryNotDefined)
		return;

	/*----- PROTECTED REGION ID(MoenchControl::init_device) ENABLED START -----*/
	/* clang-format on */
	//	Initialize device
	/* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	MoenchControl::init_device
}

//--------------------------------------------------------
/**
 *	Method      : MoenchControl::get_device_property()
 * Description:  Read database to initialize property data members.
 */
//--------------------------------------------------------
void MoenchControl::get_device_property()
{
	/*----- PROTECTED REGION ID(MoenchControl::get_device_property_before) ENABLED START -----*/
	/* clang-format on */
	//	Initialize property data members
	/* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	MoenchControl::get_device_property_before

	mandatoryNotDefined = false;

	//	Read device properties from database.
	Tango::DbData	dev_prop;
	dev_prop.push_back(Tango::DbDatum("SLS_RECEIVER_PORT"));
	dev_prop.push_back(Tango::DbDatum("PROCESSING_RX_IP"));
	dev_prop.push_back(Tango::DbDatum("PROCESSING_RX_PORT"));
	dev_prop.push_back(Tango::DbDatum("CONTROL_TX_IP"));
	dev_prop.push_back(Tango::DbDatum("CONTROL_TX_PORT"));
	dev_prop.push_back(Tango::DbDatum("MOENCHZMQ_DEVICE"));

	//	is there at least one property to be read ?
	if (dev_prop.size()>0)
	{
		//	Call database and extract values
		if (Tango::Util::instance()->_UseDb==true)
			get_db_device()->get_property(dev_prop);

		//	get instance on MoenchControlClass to get class property
		Tango::DbDatum	def_prop, cl_prop;
		MoenchControlClass	*ds_class =
			(static_cast<MoenchControlClass *>(get_device_class()));
		int	i = -1;

		//	Try to initialize SLS_RECEIVER_PORT from class property
		cl_prop = ds_class->get_class_property(dev_prop[++i].name);
		if (cl_prop.is_empty()==false)	cl_prop  >>  sLS_RECEIVER_PORT;
		else {
			//	Try to initialize SLS_RECEIVER_PORT from default device value
			def_prop = ds_class->get_default_device_property(dev_prop[i].name);
			if (def_prop.is_empty()==false)	def_prop  >>  sLS_RECEIVER_PORT;
		}
		//	And try to extract SLS_RECEIVER_PORT value from database
		if (dev_prop[i].is_empty()==false)	dev_prop[i]  >>  sLS_RECEIVER_PORT;
		//	Property StartDsPath is mandatory, check if has been defined in database.
		check_mandatory_property(cl_prop, dev_prop[i]);

		//	Try to initialize PROCESSING_RX_IP from class property
		cl_prop = ds_class->get_class_property(dev_prop[++i].name);
		if (cl_prop.is_empty()==false)	cl_prop  >>  pROCESSING_RX_IP;
		else {
			//	Try to initialize PROCESSING_RX_IP from default device value
			def_prop = ds_class->get_default_device_property(dev_prop[i].name);
			if (def_prop.is_empty()==false)	def_prop  >>  pROCESSING_RX_IP;
		}
		//	And try to extract PROCESSING_RX_IP value from database
		if (dev_prop[i].is_empty()==false)	dev_prop[i]  >>  pROCESSING_RX_IP;
		//	Property StartDsPath is mandatory, check if has been defined in database.
		check_mandatory_property(cl_prop, dev_prop[i]);

		//	Try to initialize PROCESSING_RX_PORT from class property
		cl_prop = ds_class->get_class_property(dev_prop[++i].name);
		if (cl_prop.is_empty()==false)	cl_prop  >>  pROCESSING_RX_PORT;
		else {
			//	Try to initialize PROCESSING_RX_PORT from default device value
			def_prop = ds_class->get_default_device_property(dev_prop[i].name);
			if (def_prop.is_empty()==false)	def_prop  >>  pROCESSING_RX_PORT;
		}
		//	And try to extract PROCESSING_RX_PORT value from database
		if (dev_prop[i].is_empty()==false)	dev_prop[i]  >>  pROCESSING_RX_PORT;
		//	Property StartDsPath is mandatory, check if has been defined in database.
		check_mandatory_property(cl_prop, dev_prop[i]);

		//	Try to initialize CONTROL_TX_IP from class property
		cl_prop = ds_class->get_class_property(dev_prop[++i].name);
		if (cl_prop.is_empty()==false)	cl_prop  >>  cONTROL_TX_IP;
		else {
			//	Try to initialize CONTROL_TX_IP from default device value
			def_prop = ds_class->get_default_device_property(dev_prop[i].name);
			if (def_prop.is_empty()==false)	def_prop  >>  cONTROL_TX_IP;
		}
		//	And try to extract CONTROL_TX_IP value from database
		if (dev_prop[i].is_empty()==false)	dev_prop[i]  >>  cONTROL_TX_IP;
		//	Property StartDsPath is mandatory, check if has been defined in database.
		check_mandatory_property(cl_prop, dev_prop[i]);

		//	Try to initialize CONTROL_TX_PORT from class property
		cl_prop = ds_class->get_class_property(dev_prop[++i].name);
		if (cl_prop.is_empty()==false)	cl_prop  >>  cONTROL_TX_PORT;
		else {
			//	Try to initialize CONTROL_TX_PORT from default device value
			def_prop = ds_class->get_default_device_property(dev_prop[i].name);
			if (def_prop.is_empty()==false)	def_prop  >>  cONTROL_TX_PORT;
		}
		//	And try to extract CONTROL_TX_PORT value from database
		if (dev_prop[i].is_empty()==false)	dev_prop[i]  >>  cONTROL_TX_PORT;
		//	Property StartDsPath is mandatory, check if has been defined in database.
		check_mandatory_property(cl_prop, dev_prop[i]);

		//	Try to initialize MOENCHZMQ_DEVICE from class property
		cl_prop = ds_class->get_class_property(dev_prop[++i].name);
		if (cl_prop.is_empty()==false)	cl_prop  >>  mOENCHZMQ_DEVICE;
		else {
			//	Try to initialize MOENCHZMQ_DEVICE from default device value
			def_prop = ds_class->get_default_device_property(dev_prop[i].name);
			if (def_prop.is_empty()==false)	def_prop  >>  mOENCHZMQ_DEVICE;
		}
		//	And try to extract MOENCHZMQ_DEVICE value from database
		if (dev_prop[i].is_empty()==false)	dev_prop[i]  >>  mOENCHZMQ_DEVICE;
		//	Property StartDsPath is mandatory, check if has been defined in database.
		check_mandatory_property(cl_prop, dev_prop[i]);

	}

	/*----- PROTECTED REGION ID(MoenchControl::get_device_property_after) ENABLED START -----*/
	/* clang-format on */
	//	Check device property data members init
	/* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	MoenchControl::get_device_property_after
}
//--------------------------------------------------------
/**
 *	Method      : MoenchControl::check_mandatory_property()
 * Description:  For mandatory properties check if defined in database.
 */
//--------------------------------------------------------
void MoenchControl::check_mandatory_property(Tango::DbDatum &class_prop, Tango::DbDatum &dev_prop)
{
	//	Check if all properties are empty
	if (class_prop.is_empty() && dev_prop.is_empty())
	{
		TangoSys_OMemStream	tms;
		tms << std::endl <<"Property \'" << dev_prop.name;
		if (Tango::Util::instance()->_UseDb==true)
			tms << "\' is mandatory but not defined in database";
		else
			tms << "\' is mandatory but cannot be defined without database";
		append_status(tms.str());
		mandatoryNotDefined = true;
		/*----- PROTECTED REGION ID(MoenchControl::check_mandatory_property) ENABLED START -----*/
		/* clang-format on */
		std::cerr << tms.str() << " for " << device_name << std::endl;
		/* clang-format off */
		/*----- PROTECTED REGION END -----*/	//	MoenchControl::check_mandatory_property
	}
}


//--------------------------------------------------------
/**
 *	Method      : MoenchControl::always_executed_hook()
 * Description:  method always executed before any command is executed
 */
//--------------------------------------------------------
void MoenchControl::always_executed_hook()
{
	DEBUG_STREAM << "MoenchControl::always_executed_hook()  " << device_name << std::endl;
	if (mandatoryNotDefined)
	{
		Tango::Except::throw_exception(
					(const char *)"PROPERTY_NOT_SET",
					get_status().c_str(),
					(const char *)"MoenchControl::always_executed_hook()");
	}
	/*----- PROTECTED REGION ID(MoenchControl::always_executed_hook) ENABLED START -----*/
	/* clang-format on */
	//	code always executed before all requests
	/* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	MoenchControl::always_executed_hook
}

//--------------------------------------------------------
/**
 *	Method      : MoenchControl::read_attr_hardware()
 * Description:  Hardware acquisition for attributes
 */
//--------------------------------------------------------
void MoenchControl::read_attr_hardware(TANGO_UNUSED(std::vector<long> &attr_list))
{
	DEBUG_STREAM << "MoenchControl::read_attr_hardware(std::vector<long> &attr_list) entering... " << std::endl;
	/*----- PROTECTED REGION ID(MoenchControl::read_attr_hardware) ENABLED START -----*/
	/* clang-format on */
	//	Add your own code
	/* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	MoenchControl::read_attr_hardware
}
//--------------------------------------------------------
/**
 *	Method      : MoenchControl::write_attr_hardware()
 * Description:  Hardware writing for attributes
 */
//--------------------------------------------------------
void MoenchControl::write_attr_hardware(TANGO_UNUSED(std::vector<long> &attr_list))
{
	DEBUG_STREAM << "MoenchControl::write_attr_hardware(std::vector<long> &attr_list) entering... " << std::endl;
	/*----- PROTECTED REGION ID(MoenchControl::write_attr_hardware) ENABLED START -----*/
	/* clang-format on */
	//	Add your own code
	/* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	MoenchControl::write_attr_hardware
}

//--------------------------------------------------------
/**
 *	Read attribute exposure related method
 *
 *
 *	Data type:	Tango::DevFloat
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void MoenchControl::read_exposure(Tango::Attribute &attr)
{
	DEBUG_STREAM << "MoenchControl::read_exposure(Tango::Attribute &attr) entering... " << std::endl;
	/*----- PROTECTED REGION ID(MoenchControl::read_exposure) ENABLED START -----*/
	/* clang-format on */
	//	Set the attribute value
	attr.set_value(attr_exposure_read);
	/* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	MoenchControl::read_exposure
}
//--------------------------------------------------------
/**
 *	Write attribute exposure related method
 *
 *
 *	Data type:	Tango::DevFloat
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void MoenchControl::write_exposure(Tango::WAttribute &attr)
{
	DEBUG_STREAM << "MoenchControl::write_exposure(Tango::WAttribute &attr) entering... " << std::endl;
	//	Retrieve write value
	Tango::DevFloat	w_val;
	attr.get_write_value(w_val);
	/*----- PROTECTED REGION ID(MoenchControl::write_exposure) ENABLED START -----*/
	/* clang-format on */
	//	Add your own code
	/* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	MoenchControl::write_exposure
}
//--------------------------------------------------------
/**
 *	Read attribute delay related method
 *
 *
 *	Data type:	Tango::DevFloat
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void MoenchControl::read_delay(Tango::Attribute &attr)
{
	DEBUG_STREAM << "MoenchControl::read_delay(Tango::Attribute &attr) entering... " << std::endl;
	/*----- PROTECTED REGION ID(MoenchControl::read_delay) ENABLED START -----*/
	/* clang-format on */
	//	Set the attribute value
	attr.set_value(attr_delay_read);
	/* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	MoenchControl::read_delay
}
//--------------------------------------------------------
/**
 *	Write attribute delay related method
 *
 *
 *	Data type:	Tango::DevFloat
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void MoenchControl::write_delay(Tango::WAttribute &attr)
{
	DEBUG_STREAM << "MoenchControl::write_delay(Tango::WAttribute &attr) entering... " << std::endl;
	//	Retrieve write value
	Tango::DevFloat	w_val;
	attr.get_write_value(w_val);
	/*----- PROTECTED REGION ID(MoenchControl::write_delay) ENABLED START -----*/
	/* clang-format on */
	//	Add your own code
	/* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	MoenchControl::write_delay
}
//--------------------------------------------------------
/**
 *	Read attribute timing_mode related method
 *
 *
 *	Data type:	Tango::DevEnum (timing_modeEnum)
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void MoenchControl::read_timing_mode(Tango::Attribute &attr)
{
	DEBUG_STREAM << "MoenchControl::read_timing_mode(Tango::Attribute &attr) entering... " << std::endl;
	/*----- PROTECTED REGION ID(MoenchControl::read_timing_mode) ENABLED START -----*/
	/* clang-format on */
	//	Set the attribute value
	attr.set_value(attr_timing_mode_read);
	/* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	MoenchControl::read_timing_mode
}
//--------------------------------------------------------
/**
 *	Write attribute timing_mode related method
 *
 *
 *	Data type:	Tango::DevEnum (timing_modeEnum)
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void MoenchControl::write_timing_mode(Tango::WAttribute &attr)
{
	DEBUG_STREAM << "MoenchControl::write_timing_mode(Tango::WAttribute &attr) entering... " << std::endl;
	//	Retrieve write value
	timing_modeEnum	w_val;
	attr.get_write_value(w_val);
	/*----- PROTECTED REGION ID(MoenchControl::write_timing_mode) ENABLED START -----*/
	/* clang-format on */
	//	Add your own code
	/* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	MoenchControl::write_timing_mode
}
//--------------------------------------------------------
/**
 *	Read attribute triggers related method
 *
 *
 *	Data type:	Tango::DevLong64
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void MoenchControl::read_triggers(Tango::Attribute &attr)
{
	DEBUG_STREAM << "MoenchControl::read_triggers(Tango::Attribute &attr) entering... " << std::endl;
	/*----- PROTECTED REGION ID(MoenchControl::read_triggers) ENABLED START -----*/
	/* clang-format on */
	//	Set the attribute value
	attr.set_value(attr_triggers_read);
	/* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	MoenchControl::read_triggers
}
//--------------------------------------------------------
/**
 *	Write attribute triggers related method
 *
 *
 *	Data type:	Tango::DevLong64
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void MoenchControl::write_triggers(Tango::WAttribute &attr)
{
	DEBUG_STREAM << "MoenchControl::write_triggers(Tango::WAttribute &attr) entering... " << std::endl;
	//	Retrieve write value
	Tango::DevLong64	w_val;
	attr.get_write_value(w_val);
	/*----- PROTECTED REGION ID(MoenchControl::write_triggers) ENABLED START -----*/
	/* clang-format on */
	//	Add your own code
	/* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	MoenchControl::write_triggers
}
//--------------------------------------------------------
/**
 *	Read attribute frames related method
 *
 *
 *	Data type:	Tango::DevLong64
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void MoenchControl::read_frames(Tango::Attribute &attr)
{
	DEBUG_STREAM << "MoenchControl::read_frames(Tango::Attribute &attr) entering... " << std::endl;
	/*----- PROTECTED REGION ID(MoenchControl::read_frames) ENABLED START -----*/
	/* clang-format on */
	//	Set the attribute value
	attr.set_value(attr_frames_read);
	/* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	MoenchControl::read_frames
}
//--------------------------------------------------------
/**
 *	Write attribute frames related method
 *
 *
 *	Data type:	Tango::DevLong64
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void MoenchControl::write_frames(Tango::WAttribute &attr)
{
	DEBUG_STREAM << "MoenchControl::write_frames(Tango::WAttribute &attr) entering... " << std::endl;
	//	Retrieve write value
	Tango::DevLong64	w_val;
	attr.get_write_value(w_val);
	/*----- PROTECTED REGION ID(MoenchControl::write_frames) ENABLED START -----*/
	/* clang-format on */
	//	Add your own code
	/* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	MoenchControl::write_frames
}
//--------------------------------------------------------
/**
 *	Read attribute high_voltage related method
 *
 *
 *	Data type:	Tango::DevLong64
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void MoenchControl::read_high_voltage(Tango::Attribute &attr)
{
	DEBUG_STREAM << "MoenchControl::read_high_voltage(Tango::Attribute &attr) entering... " << std::endl;
	/*----- PROTECTED REGION ID(MoenchControl::read_high_voltage) ENABLED START -----*/
	/* clang-format on */
	//	Set the attribute value
	attr.set_value(attr_high_voltage_read);
	/* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	MoenchControl::read_high_voltage
}
//--------------------------------------------------------
/**
 *	Write attribute high_voltage related method
 *
 *
 *	Data type:	Tango::DevLong64
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void MoenchControl::write_high_voltage(Tango::WAttribute &attr)
{
	DEBUG_STREAM << "MoenchControl::write_high_voltage(Tango::WAttribute &attr) entering... " << std::endl;
	//	Retrieve write value
	Tango::DevLong64	w_val;
	attr.get_write_value(w_val);
	/*----- PROTECTED REGION ID(MoenchControl::write_high_voltage) ENABLED START -----*/
	/* clang-format on */
	//	Add your own code
	/* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	MoenchControl::write_high_voltage
}
//--------------------------------------------------------
/**
 *	Read attribute gain_mode related method
 *
 *
 *	Data type:	Tango::DevEnum (gain_modeEnum)
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void MoenchControl::read_gain_mode(Tango::Attribute &attr)
{
	DEBUG_STREAM << "MoenchControl::read_gain_mode(Tango::Attribute &attr) entering... " << std::endl;
	/*----- PROTECTED REGION ID(MoenchControl::read_gain_mode) ENABLED START -----*/
	/* clang-format on */
	//	Set the attribute value
	attr.set_value(attr_gain_mode_read);
	/* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	MoenchControl::read_gain_mode
}
//--------------------------------------------------------
/**
 *	Write attribute gain_mode related method
 *
 *
 *	Data type:	Tango::DevEnum (gain_modeEnum)
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void MoenchControl::write_gain_mode(Tango::WAttribute &attr)
{
	DEBUG_STREAM << "MoenchControl::write_gain_mode(Tango::WAttribute &attr) entering... " << std::endl;
	//	Retrieve write value
	gain_modeEnum	w_val;
	attr.get_write_value(w_val);
	/*----- PROTECTED REGION ID(MoenchControl::write_gain_mode) ENABLED START -----*/
	/* clang-format on */
	//	Add your own code
	/* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	MoenchControl::write_gain_mode
}
//--------------------------------------------------------
/**
 *	Read attribute period related method
 *
 *
 *	Data type:	Tango::DevFloat
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void MoenchControl::read_period(Tango::Attribute &attr)
{
	DEBUG_STREAM << "MoenchControl::read_period(Tango::Attribute &attr) entering... " << std::endl;
	/*----- PROTECTED REGION ID(MoenchControl::read_period) ENABLED START -----*/
	/* clang-format on */
	//	Set the attribute value
	attr.set_value(attr_period_read);
	/* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	MoenchControl::read_period
}
//--------------------------------------------------------
/**
 *	Write attribute period related method
 *
 *
 *	Data type:	Tango::DevFloat
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void MoenchControl::write_period(Tango::WAttribute &attr)
{
	DEBUG_STREAM << "MoenchControl::write_period(Tango::WAttribute &attr) entering... " << std::endl;
	//	Retrieve write value
	Tango::DevFloat	w_val;
	attr.get_write_value(w_val);
	/*----- PROTECTED REGION ID(MoenchControl::write_period) ENABLED START -----*/
	/* clang-format on */
	//	Add your own code
	/* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	MoenchControl::write_period
}
//--------------------------------------------------------
/**
 *	Read attribute zmq_rx_ip related method
 *
 *
 *	Data type:	Tango::DevString
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void MoenchControl::read_zmq_rx_ip(Tango::Attribute &attr)
{
	DEBUG_STREAM << "MoenchControl::read_zmq_rx_ip(Tango::Attribute &attr) entering... " << std::endl;
	/*----- PROTECTED REGION ID(MoenchControl::read_zmq_rx_ip) ENABLED START -----*/
	/* clang-format on */
	//	Set the attribute value
	attr.set_value(attr_zmq_rx_ip_read);
	/* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	MoenchControl::read_zmq_rx_ip
}
//--------------------------------------------------------
/**
 *	Write attribute zmq_rx_ip related method
 *
 *
 *	Data type:	Tango::DevString
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void MoenchControl::write_zmq_rx_ip(Tango::WAttribute &attr)
{
	DEBUG_STREAM << "MoenchControl::write_zmq_rx_ip(Tango::WAttribute &attr) entering... " << std::endl;
	//	Retrieve write value
	Tango::DevString	w_val;
	attr.get_write_value(w_val);
	/*----- PROTECTED REGION ID(MoenchControl::write_zmq_rx_ip) ENABLED START -----*/
	/* clang-format on */
	//	Add your own code
	/* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	MoenchControl::write_zmq_rx_ip
}
//--------------------------------------------------------
/**
 *	Read attribute zmq_rx_port related method
 *
 *
 *	Data type:	Tango::DevLong64
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void MoenchControl::read_zmq_rx_port(Tango::Attribute &attr)
{
	DEBUG_STREAM << "MoenchControl::read_zmq_rx_port(Tango::Attribute &attr) entering... " << std::endl;
	/*----- PROTECTED REGION ID(MoenchControl::read_zmq_rx_port) ENABLED START -----*/
	/* clang-format on */
	//	Set the attribute value
	attr.set_value(attr_zmq_rx_port_read);
	/* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	MoenchControl::read_zmq_rx_port
}
//--------------------------------------------------------
/**
 *	Write attribute zmq_rx_port related method
 *
 *
 *	Data type:	Tango::DevLong64
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void MoenchControl::write_zmq_rx_port(Tango::WAttribute &attr)
{
	DEBUG_STREAM << "MoenchControl::write_zmq_rx_port(Tango::WAttribute &attr) entering... " << std::endl;
	//	Retrieve write value
	Tango::DevLong64	w_val;
	attr.get_write_value(w_val);
	/*----- PROTECTED REGION ID(MoenchControl::write_zmq_rx_port) ENABLED START -----*/
	/* clang-format on */
	//	Add your own code
	/* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	MoenchControl::write_zmq_rx_port
}
//--------------------------------------------------------
/**
 *	Read attribute rx_discard_policy related method
 *
 *
 *	Data type:	Tango::DevEnum (rx_discard_policyEnum)
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void MoenchControl::read_rx_discard_policy(Tango::Attribute &attr)
{
	DEBUG_STREAM << "MoenchControl::read_rx_discard_policy(Tango::Attribute &attr) entering... " << std::endl;
	/*----- PROTECTED REGION ID(MoenchControl::read_rx_discard_policy) ENABLED START -----*/
	/* clang-format on */
	//	Set the attribute value
	attr.set_value(attr_rx_discard_policy_read);
	/* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	MoenchControl::read_rx_discard_policy
}
//--------------------------------------------------------
/**
 *	Write attribute rx_discard_policy related method
 *
 *
 *	Data type:	Tango::DevEnum (rx_discard_policyEnum)
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void MoenchControl::write_rx_discard_policy(Tango::WAttribute &attr)
{
	DEBUG_STREAM << "MoenchControl::write_rx_discard_policy(Tango::WAttribute &attr) entering... " << std::endl;
	//	Retrieve write value
	rx_discard_policyEnum	w_val;
	attr.get_write_value(w_val);
	/*----- PROTECTED REGION ID(MoenchControl::write_rx_discard_policy) ENABLED START -----*/
	/* clang-format on */
	//	Add your own code
	/* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	MoenchControl::write_rx_discard_policy
}
//--------------------------------------------------------
/**
 *	Read attribute rx_hostname related method
 *
 *
 *	Data type:	Tango::DevString
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void MoenchControl::read_rx_hostname(Tango::Attribute &attr)
{
	DEBUG_STREAM << "MoenchControl::read_rx_hostname(Tango::Attribute &attr) entering... " << std::endl;
	/*----- PROTECTED REGION ID(MoenchControl::read_rx_hostname) ENABLED START -----*/
	/* clang-format on */
	//	Set the attribute value
	attr.set_value(attr_rx_hostname_read);
	/* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	MoenchControl::read_rx_hostname
}
//--------------------------------------------------------
/**
 *	Write attribute rx_hostname related method
 *
 *
 *	Data type:	Tango::DevString
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void MoenchControl::write_rx_hostname(Tango::WAttribute &attr)
{
	DEBUG_STREAM << "MoenchControl::write_rx_hostname(Tango::WAttribute &attr) entering... " << std::endl;
	//	Retrieve write value
	Tango::DevString	w_val;
	attr.get_write_value(w_val);
	/*----- PROTECTED REGION ID(MoenchControl::write_rx_hostname) ENABLED START -----*/
	/* clang-format on */
	//	Add your own code
	/* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	MoenchControl::write_rx_hostname
}
//--------------------------------------------------------
/**
 *	Read attribute rx_tcp_port related method
 *
 *
 *	Data type:	Tango::DevLong64
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void MoenchControl::read_rx_tcp_port(Tango::Attribute &attr)
{
	DEBUG_STREAM << "MoenchControl::read_rx_tcp_port(Tango::Attribute &attr) entering... " << std::endl;
	/*----- PROTECTED REGION ID(MoenchControl::read_rx_tcp_port) ENABLED START -----*/
	/* clang-format on */
	//	Set the attribute value
	attr.set_value(attr_rx_tcp_port_read);
	/* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	MoenchControl::read_rx_tcp_port
}
//--------------------------------------------------------
/**
 *	Write attribute rx_tcp_port related method
 *
 *
 *	Data type:	Tango::DevLong64
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void MoenchControl::write_rx_tcp_port(Tango::WAttribute &attr)
{
	DEBUG_STREAM << "MoenchControl::write_rx_tcp_port(Tango::WAttribute &attr) entering... " << std::endl;
	//	Retrieve write value
	Tango::DevLong64	w_val;
	attr.get_write_value(w_val);
	/*----- PROTECTED REGION ID(MoenchControl::write_rx_tcp_port) ENABLED START -----*/
	/* clang-format on */
	//	Add your own code
	/* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	MoenchControl::write_rx_tcp_port
}
//--------------------------------------------------------
/**
 *	Read attribute detector_status related method
 *
 *
 *	Data type:	Tango::DevEnum (detector_statusEnum)
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void MoenchControl::read_detector_status(Tango::Attribute &attr)
{
	DEBUG_STREAM << "MoenchControl::read_detector_status(Tango::Attribute &attr) entering... " << std::endl;
	/*----- PROTECTED REGION ID(MoenchControl::read_detector_status) ENABLED START -----*/
	/* clang-format on */
	//	Set the attribute value
	attr.set_value(attr_detector_status_read);
	/* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	MoenchControl::read_detector_status
}
//--------------------------------------------------------
/**
 *	Read attribute rx_zmq_data_stream related method
 *
 *
 *	Data type:	Tango::DevBoolean
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void MoenchControl::read_rx_zmq_data_stream(Tango::Attribute &attr)
{
	DEBUG_STREAM << "MoenchControl::read_rx_zmq_data_stream(Tango::Attribute &attr) entering... " << std::endl;
	/*----- PROTECTED REGION ID(MoenchControl::read_rx_zmq_data_stream) ENABLED START -----*/
	/* clang-format on */
	//	Set the attribute value
	attr.set_value(attr_rx_zmq_data_stream_read);
	/* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	MoenchControl::read_rx_zmq_data_stream
}
//--------------------------------------------------------
/**
 *	Write attribute rx_zmq_data_stream related method
 *
 *
 *	Data type:	Tango::DevBoolean
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void MoenchControl::write_rx_zmq_data_stream(Tango::WAttribute &attr)
{
	DEBUG_STREAM << "MoenchControl::write_rx_zmq_data_stream(Tango::WAttribute &attr) entering... " << std::endl;
	//	Retrieve write value
	Tango::DevBoolean	w_val;
	attr.get_write_value(w_val);
	/*----- PROTECTED REGION ID(MoenchControl::write_rx_zmq_data_stream) ENABLED START -----*/
	/* clang-format on */
	//	Add your own code
	/* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	MoenchControl::write_rx_zmq_data_stream
}

//--------------------------------------------------------
/**
 *	Method      : MoenchControl::add_dynamic_attributes()
 * Description:  Create the dynamic attributes if any
 *                for specified device.
 */
//--------------------------------------------------------
void MoenchControl::add_dynamic_attributes()
{
	/*----- PROTECTED REGION ID(MoenchControl::add_dynamic_attributes) ENABLED START -----*/
	/* clang-format on */
	//	Add your own code to create and add dynamic attributes if any
	/* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	MoenchControl::add_dynamic_attributes
}

//--------------------------------------------------------
/**
 *	Method      : MoenchControl::add_dynamic_commands()
 * Description:  Create the dynamic commands if any
 *                for specified device.
 */
//--------------------------------------------------------
void MoenchControl::add_dynamic_commands()
{
	/*----- PROTECTED REGION ID(MoenchControl::add_dynamic_commands) ENABLED START -----*/
	/* clang-format on */
	//	Add your own code to create and add dynamic commands if any
	/* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	MoenchControl::add_dynamic_commands
}

/*----- PROTECTED REGION ID(MoenchControl::namespace_ending) ENABLED START -----*/
/* clang-format on */
//	Additional Methods
/* clang-format off */
/*----- PROTECTED REGION END -----*/	//	MoenchControl::namespace_ending
} //	namespace
