/*----- PROTECTED REGION ID(MoenchControlStateMachine.cpp) ENABLED START -----*/
/* clang-format on */
//=============================================================================
//
// file :        MoenchControlStateMachine.cpp
//
// description : State machine file for the MoenchControl class
//
// project :     Tango device for control of MOENCH detector
//
// This file is part of Tango device class.
//
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
//
//
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================

#include "MoenchControl.h"

/* clang-format off */
/*----- PROTECTED REGION END -----*/	//	MoenchControl::MoenchControlStateMachine.cpp

//================================================================
//  States  |  Description
//================================================================


namespace MoenchControl_ns
{
//=================================================
//		Attributes Allowed Methods
//=================================================

//--------------------------------------------------------
/**
 *	Method      : MoenchControl::is_exposure_allowed()
 * Description:  Execution allowed for exposure attribute
 */
//--------------------------------------------------------
bool MoenchControl::is_exposure_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for exposure attribute in Write access.
	/*----- PROTECTED REGION ID(MoenchControl::exposureStateAllowed_WRITE) ENABLED START -----*/
	/* clang-format on */
	/* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	MoenchControl::exposureStateAllowed_WRITE

	//	Not any excluded states for exposure attribute in read access.
	/*----- PROTECTED REGION ID(MoenchControl::exposureStateAllowed_READ) ENABLED START -----*/
	/* clang-format on */
	/* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	MoenchControl::exposureStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : MoenchControl::is_delay_allowed()
 * Description:  Execution allowed for delay attribute
 */
//--------------------------------------------------------
bool MoenchControl::is_delay_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for delay attribute in Write access.
	/*----- PROTECTED REGION ID(MoenchControl::delayStateAllowed_WRITE) ENABLED START -----*/
	/* clang-format on */
	/* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	MoenchControl::delayStateAllowed_WRITE

	//	Not any excluded states for delay attribute in read access.
	/*----- PROTECTED REGION ID(MoenchControl::delayStateAllowed_READ) ENABLED START -----*/
	/* clang-format on */
	/* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	MoenchControl::delayStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : MoenchControl::is_timing_mode_allowed()
 * Description:  Execution allowed for timing_mode attribute
 */
//--------------------------------------------------------
bool MoenchControl::is_timing_mode_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for timing_mode attribute in Write access.
	/*----- PROTECTED REGION ID(MoenchControl::timing_modeStateAllowed_WRITE) ENABLED START -----*/
	/* clang-format on */
	/* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	MoenchControl::timing_modeStateAllowed_WRITE

	//	Not any excluded states for timing_mode attribute in read access.
	/*----- PROTECTED REGION ID(MoenchControl::timing_modeStateAllowed_READ) ENABLED START -----*/
	/* clang-format on */
	/* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	MoenchControl::timing_modeStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : MoenchControl::is_triggers_allowed()
 * Description:  Execution allowed for triggers attribute
 */
//--------------------------------------------------------
bool MoenchControl::is_triggers_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for triggers attribute in Write access.
	/*----- PROTECTED REGION ID(MoenchControl::triggersStateAllowed_WRITE) ENABLED START -----*/
	/* clang-format on */
	/* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	MoenchControl::triggersStateAllowed_WRITE

	//	Not any excluded states for triggers attribute in read access.
	/*----- PROTECTED REGION ID(MoenchControl::triggersStateAllowed_READ) ENABLED START -----*/
	/* clang-format on */
	/* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	MoenchControl::triggersStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : MoenchControl::is_frames_allowed()
 * Description:  Execution allowed for frames attribute
 */
//--------------------------------------------------------
bool MoenchControl::is_frames_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for frames attribute in Write access.
	/*----- PROTECTED REGION ID(MoenchControl::framesStateAllowed_WRITE) ENABLED START -----*/
	/* clang-format on */
	/* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	MoenchControl::framesStateAllowed_WRITE

	//	Not any excluded states for frames attribute in read access.
	/*----- PROTECTED REGION ID(MoenchControl::framesStateAllowed_READ) ENABLED START -----*/
	/* clang-format on */
	/* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	MoenchControl::framesStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : MoenchControl::is_high_voltage_allowed()
 * Description:  Execution allowed for high_voltage attribute
 */
//--------------------------------------------------------
bool MoenchControl::is_high_voltage_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for high_voltage attribute in Write access.
	/*----- PROTECTED REGION ID(MoenchControl::high_voltageStateAllowed_WRITE) ENABLED START -----*/
	/* clang-format on */
	/* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	MoenchControl::high_voltageStateAllowed_WRITE

	//	Not any excluded states for high_voltage attribute in read access.
	/*----- PROTECTED REGION ID(MoenchControl::high_voltageStateAllowed_READ) ENABLED START -----*/
	/* clang-format on */
	/* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	MoenchControl::high_voltageStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : MoenchControl::is_gain_mode_allowed()
 * Description:  Execution allowed for gain_mode attribute
 */
//--------------------------------------------------------
bool MoenchControl::is_gain_mode_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for gain_mode attribute in Write access.
	/*----- PROTECTED REGION ID(MoenchControl::gain_modeStateAllowed_WRITE) ENABLED START -----*/
	/* clang-format on */
	/* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	MoenchControl::gain_modeStateAllowed_WRITE

	//	Not any excluded states for gain_mode attribute in read access.
	/*----- PROTECTED REGION ID(MoenchControl::gain_modeStateAllowed_READ) ENABLED START -----*/
	/* clang-format on */
	/* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	MoenchControl::gain_modeStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : MoenchControl::is_period_allowed()
 * Description:  Execution allowed for period attribute
 */
//--------------------------------------------------------
bool MoenchControl::is_period_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for period attribute in Write access.
	/*----- PROTECTED REGION ID(MoenchControl::periodStateAllowed_WRITE) ENABLED START -----*/
	/* clang-format on */
	/* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	MoenchControl::periodStateAllowed_WRITE

	//	Not any excluded states for period attribute in read access.
	/*----- PROTECTED REGION ID(MoenchControl::periodStateAllowed_READ) ENABLED START -----*/
	/* clang-format on */
	/* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	MoenchControl::periodStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : MoenchControl::is_zmq_rx_ip_allowed()
 * Description:  Execution allowed for zmq_rx_ip attribute
 */
//--------------------------------------------------------
bool MoenchControl::is_zmq_rx_ip_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for zmq_rx_ip attribute in Write access.
	/*----- PROTECTED REGION ID(MoenchControl::zmq_rx_ipStateAllowed_WRITE) ENABLED START -----*/
	/* clang-format on */
	/* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	MoenchControl::zmq_rx_ipStateAllowed_WRITE

	//	Not any excluded states for zmq_rx_ip attribute in read access.
	/*----- PROTECTED REGION ID(MoenchControl::zmq_rx_ipStateAllowed_READ) ENABLED START -----*/
	/* clang-format on */
	/* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	MoenchControl::zmq_rx_ipStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : MoenchControl::is_zmq_rx_port_allowed()
 * Description:  Execution allowed for zmq_rx_port attribute
 */
//--------------------------------------------------------
bool MoenchControl::is_zmq_rx_port_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for zmq_rx_port attribute in Write access.
	/*----- PROTECTED REGION ID(MoenchControl::zmq_rx_portStateAllowed_WRITE) ENABLED START -----*/
	/* clang-format on */
	/* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	MoenchControl::zmq_rx_portStateAllowed_WRITE

	//	Not any excluded states for zmq_rx_port attribute in read access.
	/*----- PROTECTED REGION ID(MoenchControl::zmq_rx_portStateAllowed_READ) ENABLED START -----*/
	/* clang-format on */
	/* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	MoenchControl::zmq_rx_portStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : MoenchControl::is_rx_discard_policy_allowed()
 * Description:  Execution allowed for rx_discard_policy attribute
 */
//--------------------------------------------------------
bool MoenchControl::is_rx_discard_policy_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for rx_discard_policy attribute in Write access.
	/*----- PROTECTED REGION ID(MoenchControl::rx_discard_policyStateAllowed_WRITE) ENABLED START -----*/
	/* clang-format on */
	/* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	MoenchControl::rx_discard_policyStateAllowed_WRITE

	//	Not any excluded states for rx_discard_policy attribute in read access.
	/*----- PROTECTED REGION ID(MoenchControl::rx_discard_policyStateAllowed_READ) ENABLED START -----*/
	/* clang-format on */
	/* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	MoenchControl::rx_discard_policyStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : MoenchControl::is_rx_hostname_allowed()
 * Description:  Execution allowed for rx_hostname attribute
 */
//--------------------------------------------------------
bool MoenchControl::is_rx_hostname_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for rx_hostname attribute in Write access.
	/*----- PROTECTED REGION ID(MoenchControl::rx_hostnameStateAllowed_WRITE) ENABLED START -----*/
	/* clang-format on */
	/* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	MoenchControl::rx_hostnameStateAllowed_WRITE

	//	Not any excluded states for rx_hostname attribute in read access.
	/*----- PROTECTED REGION ID(MoenchControl::rx_hostnameStateAllowed_READ) ENABLED START -----*/
	/* clang-format on */
	/* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	MoenchControl::rx_hostnameStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : MoenchControl::is_rx_tcp_port_allowed()
 * Description:  Execution allowed for rx_tcp_port attribute
 */
//--------------------------------------------------------
bool MoenchControl::is_rx_tcp_port_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for rx_tcp_port attribute in Write access.
	/*----- PROTECTED REGION ID(MoenchControl::rx_tcp_portStateAllowed_WRITE) ENABLED START -----*/
	/* clang-format on */
	/* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	MoenchControl::rx_tcp_portStateAllowed_WRITE

	//	Not any excluded states for rx_tcp_port attribute in read access.
	/*----- PROTECTED REGION ID(MoenchControl::rx_tcp_portStateAllowed_READ) ENABLED START -----*/
	/* clang-format on */
	/* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	MoenchControl::rx_tcp_portStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : MoenchControl::is_detector_status_allowed()
 * Description:  Execution allowed for detector_status attribute
 */
//--------------------------------------------------------
bool MoenchControl::is_detector_status_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for detector_status attribute in read access.
	/*----- PROTECTED REGION ID(MoenchControl::detector_statusStateAllowed_READ) ENABLED START -----*/
	/* clang-format on */
	/* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	MoenchControl::detector_statusStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : MoenchControl::is_rx_zmq_data_stream_allowed()
 * Description:  Execution allowed for rx_zmq_data_stream attribute
 */
//--------------------------------------------------------
bool MoenchControl::is_rx_zmq_data_stream_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for rx_zmq_data_stream attribute in Write access.
	/*----- PROTECTED REGION ID(MoenchControl::rx_zmq_data_streamStateAllowed_WRITE) ENABLED START -----*/
	/* clang-format on */
	/* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	MoenchControl::rx_zmq_data_streamStateAllowed_WRITE

	//	Not any excluded states for rx_zmq_data_stream attribute in read access.
	/*----- PROTECTED REGION ID(MoenchControl::rx_zmq_data_streamStateAllowed_READ) ENABLED START -----*/
	/* clang-format on */
	/* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	MoenchControl::rx_zmq_data_streamStateAllowed_READ
	return true;
}


//=================================================
//		Commands Allowed Methods
//=================================================

//--------------------------------------------------------
/**
 *	Method      : MoenchControl::is_start_acquire_allowed()
 * Description:  Execution allowed for start_acquire attribute
 */
//--------------------------------------------------------
bool MoenchControl::is_start_acquire_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for start_acquire command.
	/*----- PROTECTED REGION ID(MoenchControl::start_acquireStateAllowed) ENABLED START -----*/
	/* clang-format on */
	/* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	MoenchControl::start_acquireStateAllowed
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : MoenchControl::is_stop_acquire_allowed()
 * Description:  Execution allowed for stop_acquire attribute
 */
//--------------------------------------------------------
bool MoenchControl::is_stop_acquire_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for stop_acquire command.
	/*----- PROTECTED REGION ID(MoenchControl::stop_acquireStateAllowed) ENABLED START -----*/
	/* clang-format on */
	/* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	MoenchControl::stop_acquireStateAllowed
	return true;
}


/*----- PROTECTED REGION ID(MoenchControl::MoenchControlStateAllowed.AdditionalMethods) ENABLED START -----*/
/* clang-format on */
//	Additional Methods
/* clang-format off */
/*----- PROTECTED REGION END -----*/	//	MoenchControl::MoenchControlStateAllowed.AdditionalMethods

}	//	End of namespace
